### ISSUE TITLE
Last line in example 39.2 is not working

### ISSUE THREAD

**Issue by matiaszabal** [brunoruviaro/A_Gentle_Introduction_To_SuperCollider#6]
SystemClock.sched(0, {a[5.rand].set(\midinote, rrand(40, 70)); rrand(1, 2)});

Will work if we use \freq and an appropiate range with rrand(40, 70).midicps  
Beautiful example, by the way.

**Comment by brunoruviaro** [comment]
Fixed. Thanks!!
