### ISSUE TITLE
[pt-branch] Título em português?

### ISSUE THREAD

**Issue by brunoruviaro** [brunoruviaro/A_Gentle_Introduction_To_SuperCollider#61]
Uma Introdução Gentil ao SuperCollider
Uma Introdução Leve ao SuperCollider
Uma Introdução Suave ao SuperCollider

...?

**Comment by rodolfovalente** [comment]
acho que gosto mais da Gentil... talvez até numa ordem mais anglófona:

"Uma Gentil Introdução ao SuperCollider"

(batendo um google de "uma gentil introdução", apareceram dois tutoriais de outras linguagens em português usando esta expressão)

**Comment by brunoruviaro** [comment]
Mudei para "Uma Gentil Introdução ao SuperCollider".
