### ISSUE TITLE
rev Extra_resources (não me deixa mexer)

### ISSUE THREAD

**Issue by rodolfovalente** [brunoruviaro/A_Gentle_Introduction_To_SuperCollider#98]
\section{Referências Extra}

Chegamos ao fim desta introdução ao SuperCollider. Algumas referências extra para estudo estão listadas aqui. Aproveite!

\begin{itemize}
\item Uma excelente série de tutorias no YouTube por Eli Fieldsteel: \url{http://www.youtube.com/playlist?list=PLPYzvS8A_rTaNDweXe6PX4CXSGq4iEWYC}. 

\item O tutorial padrão para começar no SC com Scott Wilson e James Harkins, disponível online e incluído nos arquivos de Help:  
\url{http://doc.sccode.org/Tutorials/Getting-Started/00-Getting-Started-With-SC.html}

\item Tutorial online de Nick Collins: \url{http://composerprogrammer.com/teaching/supercollider/sctutorial/tutorial.html}

\item A lista de e-mails oficial do SuperCollider é a melhor maneira de conseguir uma ajuda amigável de um grande grupo de usuários. Iniciantes são muito bem vindos para fazer perguntas nesta lista (em inglês). Você pode se inscrever aqui: \url{http://www.birmingham.ac.uk/facilities/BEAST/research/supercollider/mailinglist.aspx}

\item Descubra um grupo local de SuperCollider na sua cidade. A lista oficial de usuários do SC é a melhor maneira de descobrir se existe uma onde você mora. Se não há um grupo na sua área, comece um!

\item Muitos exemplos interessantes de códigos podem ser encontrados aqui: \url{http://sccode.org/}. Crie uma conta e compartilhe seus códigos também.

\item Já ouviu falar nos tweets de SuperCollider? \url{http://supercollider.github.io/community/sc140.html}

\end{itemize}

**Comment by rodolfovalente** [comment]
adição: não valeria colocar também o grupo SuperCollider BR do facebook?
https://www.facebook.com/groups/630981953617449/

**Comment by brunoruviaro** [comment]
Feito.
